---
- name: Install nginx
  hosts: localhost
  become: true

  tasks:

  - include_tasks: install.yaml
    with_items:
      - "nginx" 

  - name: Insert Index Page
    copy:
      src: /home/kumawat/index.html
      dest: /var/www/html/index.html

  - name: Start NGiNX
    service:
      name: nginx
      state: started
